
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const FETCH_CATEGORIES_START = 'FETCH_CATEGORIES_START'
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS'
export const FETCH_CATEGORIES_ERROR = 'FETCH_CATEGORIES_ERROR'

export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START'
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR'

export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS'
export const FETCH_PRODUCT_ERROR = 'FETCH_PRODUCT_ERROR'


export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR'

export const CATEGORY_SUCCESS = 'CATEGORY_SUCCESS'
export const CATEGORY_ERROR = 'CATEGORY_ERROR'

export const ADD_NEW_CATEGORY = 'ADD_NEW_CATEGORY'
export const CHANGE_CATEGORY = 'CHANGE_CATEGORY'

export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS'
export const DELETE_CATEGORY_ERROR = 'DELETE_CATEGORY_ERROR'


export const OPEN_MODAL_PRODUCT = 'OPEN_MODAL_PRODUCT'
export const CLOSE_MODAL_PRODUCT = 'CLOSE_MODAL_PRODUCT'

export const OPEN_MESSAGE = 'OPEN_MESSAGE'
export const CLOSE_MESSAGE = 'CLOSE_MESSAGE'

export const ADD_PRODUCT = 'ADD_PRODUCT'
export const CHANGE_PRODUCT = 'CHANGE_PRODUCT'



